/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f6f5e0',
        'on-primary': '#ffffff',
        'surface-tint': '#5e6300',
        'on-secondary-container': '#626708',
        'tertiary-container': '#ddfaff',
        'on-surface': '#1c1c10',
        'surface-container': '#f0efda',
        'surface-bright': '#fcfae5',
        'inverse-surface': '#313124',
        'outline-variant': '#c8c8ab',
        'surface-dim': '#dcdbc7',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#474832',
        'primary-fixed-dim': '#c6cf00',
        'on-primary-fixed-variant': '#464a00',
        secondary: '#5e6302',
        'secondary-fixed-dim': '#c7cd68',
        'on-secondary-fixed': '#1b1d00',
        'secondary-fixed': '#e3e981',
        'surface-variant': '#e5e3cf',
        background: '#fcfae5',
        tertiary: '#486367',
        'inverse-on-surface': '#f3f2dd',
        'primary-container': '#f4ff21',
        'on-error': '#ffffff',
        surface: '#fcfae5',
        'primary-fixed': '#e2ec00',
        'on-primary-fixed': '#1b1d00',
        'on-background': '#1c1c10',
        'surface-container-high': '#eae9d5',
        'error-container': '#ffdad6',
        primary: '#5e6300',
        outline: '#787960',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'inverse-primary': '#c6cf00',
        'on-tertiary-container': '#597479',
        'surface-container-highest': '#e5e3cf',
        'secondary-container': '#e1e67e',
        'on-primary-container': '#6f7400',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'data-timer': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        headline: ['Geist', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'data-timer': ['24px', { lineHeight: '1.0', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        xl: '64px',
        md: '24px',
        sm: '16px',
        lg: '40px',
        base: '4px',
        xs: '8px',
      },
    },
  },
  plugins: [],
}
